import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner.js";
import Card from "@/components/card";
import coffeeStoresData from "../data/5.1 coffee-stores.json";
const inter = Inter({ subsets: ["latin"] });
const handleOnBannerBtnClick = () => {
  console.log("hello");
};
export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    }, // will be passed to the page component as props
  };
}
export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Rasht stores: </h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    className={styles.card}
                    key={coffeeStore.id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl}
                    href={`/coffee-store/${coffeeStore.id}`}
                  ></Card>
                );
              })}
            </div>
          </>
        )}
        <footer className={styles.footer}><p>Contact Me: @Cyansan on Telegram</p>
        <p>Contact Me: 09010698721</p></footer>
      </main>
    </div>
  );
}
